- name: Configure PostgreSQL VM and Sample Table
  hosts: postgres_vm
  become: true
  vars_files:
    - group_vars/all.yml

  handlers:
  - name: Restart postgresql
    ansible.builtin.systemd:
      name: postgresql
      state: restarted

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install PostgreSQL server
      apt:
        name: postgresql
        state: present

    - name: Install required packages for psycopg2
      apt:
        name:
          - libpq-dev
          - build-essential
          - python3-pip  # Ensure pip is installed
        state: present

    - name: Ensure PostgreSQL is started and enabled
      systemd:
        name: postgresql
        state: started
        enabled: true

    - name: Install psycopg2 using pip
      pip:
        name: psycopg2
        state: present

    - name: Allow all hosts
      postgresql_pg_hba:
        dest: /etc/postgresql/10/main/pg_hba.conf
        databases: all
        users: all
        address: 0.0.0.0/0
        method: trust
        state: present
      become: true
      become_user: postgres
      notify:
        - Restart postgresql

    - name: 'Accept connections from all hosts'
      postgresql_set:
        name: listen_addresses
        value: "*"
      become: true
      become_user: postgres
      notify:
        - Restart postgresql

    - name: 'Disable collect loggings'
      postgresql_set:
        name: logging_collector
        value: "off"
      become: true
      become_user: postgres
      notify:
        - Restart postgresql

    - name: Create a new PostgreSQL database
      postgresql_db:
        name: "exampledb2"
        state: present
        login_user: "postgres"
        login_password: "banana"
        login_host: "localhost"
        login_port: "{{ pg_port }}"


    - name: Create a sample table in PostgreSQL
      postgresql_table:
        name: sample_table
        db: "exampledb2"
        login_host: "localhost"
        login_user: "postgres"
        login_password: "banana"
        state: present
        columns:
          - id bigserial primary key
          - name text

    - name: Populate the sample table in PostgreSQL
      postgresql_query:
        db: "exampledb2"
        query: |
          INSERT INTO sample_table (name) VALUES
            ('Sample Data 1'),
            ('Sample Data 2')
        login_user: "postgres"
        login_password: "banana"
        login_host: "localhost"
        login_port: "{{ pg_port }}"
      state: present
